name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Package apk and aar with Gradle
        run: ./gradlew assembleRelease
      - name: Archive the generated Apk
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/**/*.apk
      - name: Archive the generated Aar
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: tenextll/build/outputs/aar/*.aar
      - name: Publish aar to Maven
        run: ./gradlew publish
      - name: Upload apk to PGY
        run: curl -F 'file=@./app/build/outputs/apk/release/app-release.apk' -F '_api_key=ad083d8086866b58397d435e0b2210e9' https://www.pgyer.com/apiv2/app/upload
