name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: tenextllapp/gradlew build
      - name: Package apk with Gradle
        run: cd tenextllapp && ./gradlew assembleRelease && cd ..
      - name: Archive the generated Apk
        uses: actions/upload-artifact@v2
        with:
          path: tenextllapp/app/build/outputs/apk/**/*.apk
      - name: Publish Package
        run: cd tenextllapp && ./gradlew publish && cd ..
