name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package apk and aar with Gradle
        run: ./gradlew assembleOpensource
      - name: Publish aar to Maven
        run: ./gradlew publish
      - name: Archive the apk
        uses: actions/upload-artifact@v2
        with:
          path: apk/opensource/release/iot-link-android.apk
      - name: Upload apk to PGY
        run: |
          curl -F 'file=@app/build/outputs/apk/opensource/release/iot-link-android.apk' -F '_api_key=${{ secrets.RELEASE_PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload
