name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Package apk and aar with Gradle
        run: ./gradlew assembleOpensource
      - name: Publish aar to Maven
        run: ./gradlew publish
      - name: Archive the apk
        uses: actions/upload-artifact@v2
        with:
          path: app/build/outputs/apk/opensource/*/*.apk
      - name: Upload apk to PGY
        env:
          RELEASE_PGYER_API_KEY: ${{ secrets.RELEASE_PGYER_API_KEY }}
        run: |
          apk=$(ls app/build/outputs/apk/opensource/release/*.apk)
          curl -F "file=@${apk}" -F "_api_key=$RELEASE_PGYER_API_KEY" https://www.pgyer.com/apiv2/app/upload
